# Generated by Django 2.2.2 on 2019-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LnmpOnline2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkoutRequestID', models.CharField(max_length=200)),
                ('merchantRequestID', models.CharField(max_length=200)),
                ('resultCode', models.IntegerField()),
                ('resultDesc', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('mpesaReceiptNumber', models.CharField(max_length=50)),
                ('transactionDate', models.DateTimeField()),
                ('phoneNumber', models.CharField(max_length=15)),
            ],
        ),
    ]
