# Generated by Django 2.2.2 on 2019-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesa',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mpesa',
            name='payBill',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
