# Generated by Django 2.2.2 on 2019-07-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LnmpOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkoutRequestID', models.CharField(blank=True, default='', max_length=50)),
                ('merchantRequestID', models.CharField(blank=True, default='', max_length=50)),
                ('resultCode', models.IntegerField(null=True)),
                ('resultDesc', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.FloatField(blank=True, default=None, null=True)),
                ('mpesaReceiptNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('transactionDate', models.DateTimeField()),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
