# Generated by Django 2.2.2 on 2019-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnmpOnline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnmponline',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lnmponline',
            name='checkoutRequestID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lnmponline',
            name='merchantRequestID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lnmponline',
            name='mpesaReceiptNumber',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lnmponline',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lnmponline',
            name='resultCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lnmponline',
            name='resultDesc',
            field=models.CharField(max_length=200),
        ),
    ]
