# Generated by Django 2.2.2 on 2019-08-20 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseLeaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseleaders',
            name='Email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='baseleaders',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('base_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('base_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseLeaders.BaseLeaders')),
            ],
        ),
    ]
