# Generated by Django 2.2 on 2020-02-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseLeaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseleaders',
            name='Name',
            field=models.CharField(max_length=150),
        ),
    ]
