# Generated by Django 2.2 on 2020-02-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseLeaders', '0002_auto_20190820_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='base_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseLeaders.BaseLeaders'),
        ),
    ]
