# Generated by Django 2.2 on 2020-02-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseLeaders', '0002_auto_20200228_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseleaders',
            name='Email',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='baseleaders',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='baseleaders',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
    ]
