# Generated by Django 2.2.2 on 2019-07-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='IDNo',
            new_name='FrameNumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='RegNumber',
            new_name='FrameNumber',
        ),
    ]
