# Generated by Django 2.2.2 on 2019-07-22 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='Vehicleid',
        ),
        migrations.AlterField(
            model_name='owner',
            name='RegNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nduthiApp.Vehicle'),
        ),
    ]
