# Generated by Django 2.2.2 on 2019-08-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='BaseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseLeaders.Base'),
        ),
    ]
