# Generated by Django 2.2.2 on 2019-07-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0002_auto_20190722_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='Registration',
        ),
    ]
