# Generated by Django 2.2.2 on 2019-07-22 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0003_owner_idno'),
    ]

    operations = [
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
