# Generated by Django 2.2.2 on 2019-07-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0003_remove_insurance_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='InsuranceExpiry',
            field=models.DateField(blank=True),
        ),
    ]
