# Generated by Django 2.2.2 on 2019-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0005_auto_20190722_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='InsuranceCompany',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
