# Generated by Django 2.2.2 on 2019-07-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0006_auto_20190722_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='HasInsurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
