# Generated by Django 2.2.2 on 2019-07-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0008_auto_20190722_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='PhoneNumber',
            field=models.IntegerField(max_length=1000000000000000000),
        ),
        migrations.AlterField(
            model_name='rider',
            name='PhoneNumber',
            field=models.IntegerField(max_length=1000000000000000000),
        ),
        migrations.AlterField(
            model_name='sacco',
            name='SaccoName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
