# Generated by Django 2.2.2 on 2019-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0009_auto_20190722_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='PhoneNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rider',
            name='PhoneNumber',
            field=models.CharField(max_length=100),
        ),
    ]
