# Generated by Django 2.2.2 on 2019-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0010_auto_20190722_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='InsuranceExpiry',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='DateofBirth',
            field=models.CharField(max_length=800),
        ),
    ]
