# Generated by Django 2.2.2 on 2019-07-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0011_auto_20190723_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='InsuranceExpiry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
