# Generated by Django 2.2.2 on 2019-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nduthiApp', '0012_auto_20190723_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacco',
            name='DailyContribution',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
